services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: "postgresql://symfony_user:symfony_password@symfony_db:5432/symfony_db?serverVersion=16&charset=utf8"
      APP_ENV: dev
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
